# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

updates:
  - package-ecosystem: "composer" # Gerenciador de dependências do PHP
    directory: "/" # Caminho do arquivo composer.json
    schedule:
      interval: "daily" # Frequência das atualizações
